# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fzhan/work/meshgui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fzhan/work/meshgui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzhan/work/meshgui/CMakeFiles /home/fzhan/work/meshgui/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fzhan/work/meshgui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lightlab

# Build rule for target.
lightlab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lightlab
.PHONY : lightlab

# fast build rule for target.
lightlab/fast:
	$(MAKE) -f CMakeFiles/lightlab.dir/build.make CMakeFiles/lightlab.dir/build
.PHONY : lightlab/fast

#=============================================================================
# Target rules for targets named mesh_gui

# Build rule for target.
mesh_gui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh_gui
.PHONY : mesh_gui

# fast build rule for target.
mesh_gui/fast:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/build
.PHONY : mesh_gui/fast

#=============================================================================
# Target rules for targets named smf_view

# Build rule for target.
smf_view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smf_view
.PHONY : smf_view

# fast build rule for target.
smf_view/fast:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/build
.PHONY : smf_view/fast

#=============================================================================
# Target rules for targets named torus

# Build rule for target.
torus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 torus
.PHONY : torus

# fast build rule for target.
torus/fast:
	$(MAKE) -f CMakeFiles/torus.dir/build.make CMakeFiles/torus.dir/build
.PHONY : torus/fast

MeshGui.o: MeshGui.cpp.o
.PHONY : MeshGui.o

# target to build an object file
MeshGui.cpp.o:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/MeshGui.cpp.o
.PHONY : MeshGui.cpp.o

MeshGui.i: MeshGui.cpp.i
.PHONY : MeshGui.i

# target to preprocess a source file
MeshGui.cpp.i:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/MeshGui.cpp.i
.PHONY : MeshGui.cpp.i

MeshGui.s: MeshGui.cpp.s
.PHONY : MeshGui.s

# target to generate assembly for a file
MeshGui.cpp.s:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/MeshGui.cpp.s
.PHONY : MeshGui.cpp.s

SmfModel.o: SmfModel.cpp.o
.PHONY : SmfModel.o

# target to build an object file
SmfModel.cpp.o:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/SmfModel.cpp.o
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/SmfModel.cpp.o
.PHONY : SmfModel.cpp.o

SmfModel.i: SmfModel.cpp.i
.PHONY : SmfModel.i

# target to preprocess a source file
SmfModel.cpp.i:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/SmfModel.cpp.i
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/SmfModel.cpp.i
.PHONY : SmfModel.cpp.i

SmfModel.s: SmfModel.cpp.s
.PHONY : SmfModel.s

# target to generate assembly for a file
SmfModel.cpp.s:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/SmfModel.cpp.s
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/SmfModel.cpp.s
.PHONY : SmfModel.cpp.s

lightlab.o: lightlab.c.o
.PHONY : lightlab.o

# target to build an object file
lightlab.c.o:
	$(MAKE) -f CMakeFiles/lightlab.dir/build.make CMakeFiles/lightlab.dir/lightlab.c.o
.PHONY : lightlab.c.o

lightlab.i: lightlab.c.i
.PHONY : lightlab.i

# target to preprocess a source file
lightlab.c.i:
	$(MAKE) -f CMakeFiles/lightlab.dir/build.make CMakeFiles/lightlab.dir/lightlab.c.i
.PHONY : lightlab.c.i

lightlab.s: lightlab.c.s
.PHONY : lightlab.s

# target to generate assembly for a file
lightlab.c.s:
	$(MAKE) -f CMakeFiles/lightlab.dir/build.make CMakeFiles/lightlab.dir/lightlab.c.s
.PHONY : lightlab.c.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/smf_view.dir/build.make CMakeFiles/smf_view.dir/main.cpp.s
.PHONY : main.cpp.s

mesh_gui.o: mesh_gui.cpp.o
.PHONY : mesh_gui.o

# target to build an object file
mesh_gui.cpp.o:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/mesh_gui.cpp.o
.PHONY : mesh_gui.cpp.o

mesh_gui.i: mesh_gui.cpp.i
.PHONY : mesh_gui.i

# target to preprocess a source file
mesh_gui.cpp.i:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/mesh_gui.cpp.i
.PHONY : mesh_gui.cpp.i

mesh_gui.s: mesh_gui.cpp.s
.PHONY : mesh_gui.s

# target to generate assembly for a file
mesh_gui.cpp.s:
	$(MAKE) -f CMakeFiles/mesh_gui.dir/build.make CMakeFiles/mesh_gui.dir/mesh_gui.cpp.s
.PHONY : mesh_gui.cpp.s

torus.o: torus.cpp.o
.PHONY : torus.o

# target to build an object file
torus.cpp.o:
	$(MAKE) -f CMakeFiles/torus.dir/build.make CMakeFiles/torus.dir/torus.cpp.o
.PHONY : torus.cpp.o

torus.i: torus.cpp.i
.PHONY : torus.i

# target to preprocess a source file
torus.cpp.i:
	$(MAKE) -f CMakeFiles/torus.dir/build.make CMakeFiles/torus.dir/torus.cpp.i
.PHONY : torus.cpp.i

torus.s: torus.cpp.s
.PHONY : torus.s

# target to generate assembly for a file
torus.cpp.s:
	$(MAKE) -f CMakeFiles/torus.dir/build.make CMakeFiles/torus.dir/torus.cpp.s
.PHONY : torus.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lightlab"
	@echo "... mesh_gui"
	@echo "... rebuild_cache"
	@echo "... smf_view"
	@echo "... torus"
	@echo "... MeshGui.o"
	@echo "... MeshGui.i"
	@echo "... MeshGui.s"
	@echo "... SmfModel.o"
	@echo "... SmfModel.i"
	@echo "... SmfModel.s"
	@echo "... lightlab.o"
	@echo "... lightlab.i"
	@echo "... lightlab.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh_gui.o"
	@echo "... mesh_gui.i"
	@echo "... mesh_gui.s"
	@echo "... torus.o"
	@echo "... torus.i"
	@echo "... torus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

